
map_server:
  ros__parameters:
    use_sim_time: true
    yaml_filename: /home/akmanadm/autonomous-navigation-sim-Unity/ros2_ws/src/costmap_plugin/map/map.yaml
    frame_id: "map"
    subscribe_to_updates: true  



controller_server:
  ros__parameters:
    use_sim_time: true
    controller_frequency: 20.0

    # Use this instance name in your NavigateToPose action: controller_id = "FollowPath"
    controller_plugins: ["FollowPath"]

    FollowPath:
      plugin: "nav2_mppi_controller::MPPIController"

      # --- Sampling / rollout ---
      time_steps: 50
      model_dt: 0.05
      batch_size: 2000
      iteration_count: 2
      temperature: 0.7
      gamma: 0.02
      transform_tolerance: 0.1
      prune_distance: 1.0
      visualize: false
      reset_period: 1.0           # (only in Humble)
      regenerate_noises: false

      # --- Motion model ---
      motion_model: "Ackermann"    # <-- changed from DiffDrive

      # --- Noise std devs for control sampling ---
      # Ackermann has no lateral DOF; keep vy_* at 0.
      vx_std: 0.25
      vy_std: 0.0
      wz_std: 0.60

      # --- Velocity & accel limits ---
      # For car-like robots, you may want to forbid reverse by setting vx_min: 0.0
      vx_max: 1.0
      vx_min: -0.2                # set to 0.0 if you want no reverse
      vy_max: 0.0                  # no lateral velocity
      wz_max: 1.5

      ax_max: 5.0
      ax_min: -3.0
      ay_min: 0.0                  # no lateral accel
      ay_max: 0.0
      az_max: 2.0

      # --- Ackermann constraints ---
      AckermannConstraints:
        # Minimum turning radius of your platform (meters).
        # Tune this to your vehicle. Smaller = tighter turns.
        min_turning_r: 0.30

      # --- Visualizer (rviz, if visualize: true) ---
      TrajectoryVisualizer:
        trajectory_step: 5
        time_step: 3

      # --- Validator ---
      TrajectoryValidator:
        plugin: "mppi::DefaultOptimalTrajectoryValidator"
        collision_lookahead_time: 1.0
        consider_footprint: true

      # --- Critics ---
      critics: ["ConstraintCritic", "CostCritic", "GoalCritic", "GoalAngleCritic",
                "PathAlignCritic", "PathFollowCritic", "PathAngleCritic", "PreferForwardCritic","ObstaclesCritic"]

      ConstraintCritic:
        enabled: true
        cost_power: 1
        cost_weight: 4.0

      CostCritic:
        enabled: true
        cost_power: 1
        cost_weight: 4.0
        critical_cost: 300.0
        consider_footprint: true
        collision_cost: 1000000.0
        near_goal_distance: 1.0
        trajectory_point_step: 2

      GoalCritic:
        enabled: true
        cost_power: 1
        cost_weight: 2.0
        threshold_to_consider: 1.4

      GoalAngleCritic:
        enabled: true
        cost_power: 1
        cost_weight: 3.0
        threshold_to_consider: 0.5

      PreferForwardCritic:
        enabled: true
        cost_power: 1
        cost_weight: 3.0
        threshold_to_consider: 0.5

      PathAlignCritic:
        enabled: true
        cost_power: 1
        cost_weight: 1.5
        max_path_occupancy_ratio: 0.05
        trajectory_point_step: 4
        threshold_to_consider: 0.5
        offset_from_furthest: 20
        use_path_orientations: false

      PathFollowCritic:
        enabled: true
        cost_power: 1
        cost_weight: 2.5
        offset_from_furthest: 5
        threshold_to_consider: 1.0

      PathAngleCritic:
        enabled: true
        cost_power: 1
        cost_weight: 0.8
        offset_from_furthest: 4
        threshold_to_consider: 0.5
        max_angle_to_furthest: 1.0
        mode: 0

      ObstaclesCritic:
        enabled: true
        cost_power: 1
        repulsion_weight: 6.0
        critical_weight: 35.0
        consider_footprint: true
        collision_cost: 10000.0
        collision_margin_distance: 0.8
        near_goal_distance: 0.9

    # Progress & goal checkers
    progress_checker_plugin: "progress_checker"
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.03
      movement_time_allowance: 60.0

    goal_checker_plugins: ["goal_checker"]
    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 0.35
      stateful: true


      

local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: true
      global_frame: map
      robot_base_frame: chassis_link
      rolling_window: true
      width: 15
      height: 15
      resolution: 0.0375
      update_frequency: 10.0
      publish_frequency: 5.0

      plugins: ["static_layer", "obstacle_layer", "dynamic_human_layer","inflation_layer"]

      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_topic: "/map"
        subscribe_to_updates: true
        lethal_cost_threshold: 65
        track_unknown_space: true

      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"


      dynamic_human_layer:
        plugin: "unitycustom_layers::DynamicHumanLayer"
        enabled: true
        human_radius: 0.75
        human_core_radius: 0.45

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.35
        cost_scaling_factor: 3.0






global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: true
      robot_base_frame: chassis_link
      global_frame: map
      rolling_window: false
      track_unknown_space: true
      width: 20
      height: 20
      resolution: 0.05
      update_frequency: 1.0
      publish_frequency: 1.0
      plugins:
      - static_layer
      - obstacle_layer
      - inflation_layer

      static_layer:
        plugin: nav2_costmap_2d::StaticLayer

      obstacle_layer:
        plugin: nav2_costmap_2d::ObstacleLayer

      inflation_layer:
        plugin: nav2_costmap_2d::InflationLayer
