//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Unitycustommsg
{
    [Serializable]
    public class Point2DMsg : Message
    {
        public const string k_RosMessageName = "unitycustommsg/Point2D";
        public override string RosMessageName => k_RosMessageName;

        public double x;
        public double y;

        public Point2DMsg()
        {
            this.x = 0.0;
            this.y = 0.0;
        }

        public Point2DMsg(double x, double y)
        {
            this.x = x;
            this.y = y;
        }

        public static Point2DMsg Deserialize(MessageDeserializer deserializer) => new Point2DMsg(deserializer);

        private Point2DMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.x);
            deserializer.Read(out this.y);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.x);
            serializer.Write(this.y);
        }

        public override string ToString()
        {
            return "Point2DMsg: " +
            "\nx: " + x.ToString() +
            "\ny: " + y.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
