//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Unitycustommsg
{
    [Serializable]
    public class Point2DArrayMsg : Message
    {
        public const string k_RosMessageName = "unitycustommsg/Point2DArray";
        public override string RosMessageName => k_RosMessageName;

        public Point2DMsg[] points;

        public Point2DArrayMsg()
        {
            this.points = new Point2DMsg[0];
        }

        public Point2DArrayMsg(Point2DMsg[] points)
        {
            this.points = points;
        }

        public static Point2DArrayMsg Deserialize(MessageDeserializer deserializer) => new Point2DArrayMsg(deserializer);

        private Point2DArrayMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.points, Point2DMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.points);
            serializer.Write(this.points);
        }

        public override string ToString()
        {
            return "Point2DArrayMsg: " +
            "\npoints: " + System.String.Join(", ", points.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
