//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Unitycustommsg
{
    [Serializable]
    public class SocialMetricsMsg : Message
    {
        public const string k_RosMessageName = "unitycustommsg/SocialMetrics";
        public override string RosMessageName => k_RosMessageName;

        public double min_distance_from_static;
        public double min_distance_from_dynamic;
        public double cumulative_social_force;
        public double cumulative_static_force;
        public double cumulative_dynamic_force;
        public double social_work;

        public SocialMetricsMsg()
        {
            this.min_distance_from_static = 0.0;
            this.min_distance_from_dynamic = 0.0;
            this.cumulative_social_force = 0.0;
            this.cumulative_static_force = 0.0;
            this.cumulative_dynamic_force = 0.0;
            this.social_work = 0.0;
        }

        public SocialMetricsMsg(double min_distance_from_static, double min_distance_from_dynamic, double cumulative_social_force, double cumulative_static_force, double cumulative_dynamic_force, double social_work)
        {
            this.min_distance_from_static = min_distance_from_static;
            this.min_distance_from_dynamic = min_distance_from_dynamic;
            this.cumulative_social_force = cumulative_social_force;
            this.cumulative_static_force = cumulative_static_force;
            this.cumulative_dynamic_force = cumulative_dynamic_force;
            this.social_work = social_work;
        }

        public static SocialMetricsMsg Deserialize(MessageDeserializer deserializer) => new SocialMetricsMsg(deserializer);

        private SocialMetricsMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.min_distance_from_static);
            deserializer.Read(out this.min_distance_from_dynamic);
            deserializer.Read(out this.cumulative_social_force);
            deserializer.Read(out this.cumulative_static_force);
            deserializer.Read(out this.cumulative_dynamic_force);
            deserializer.Read(out this.social_work);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.min_distance_from_static);
            serializer.Write(this.min_distance_from_dynamic);
            serializer.Write(this.cumulative_social_force);
            serializer.Write(this.cumulative_static_force);
            serializer.Write(this.cumulative_dynamic_force);
            serializer.Write(this.social_work);
        }

        public override string ToString()
        {
            return "SocialMetricsMsg: " +
            "\nmin_distance_from_static: " + min_distance_from_static.ToString() +
            "\nmin_distance_from_dynamic: " + min_distance_from_dynamic.ToString() +
            "\ncumulative_social_force: " + cumulative_social_force.ToString() +
            "\ncumulative_static_force: " + cumulative_static_force.ToString() +
            "\ncumulative_dynamic_force: " + cumulative_dynamic_force.ToString() +
            "\nsocial_work: " + social_work.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
