//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Unitycustommsg
{
    [Serializable]
    public class TwistTransformUnityMsg : Message
    {
        public const string k_RosMessageName = "unitycustommsg/TwistTransformUnity";
        public override string RosMessageName => k_RosMessageName;

        public Geometry.TwistMsg twist;
        public Geometry.TransformStampedMsg transform;

        public TwistTransformUnityMsg()
        {
            this.twist = new Geometry.TwistMsg();
            this.transform = new Geometry.TransformStampedMsg();
        }

        public TwistTransformUnityMsg(Geometry.TwistMsg twist, Geometry.TransformStampedMsg transform)
        {
            this.twist = twist;
            this.transform = transform;
        }

        public static TwistTransformUnityMsg Deserialize(MessageDeserializer deserializer) => new TwistTransformUnityMsg(deserializer);

        private TwistTransformUnityMsg(MessageDeserializer deserializer)
        {
            this.twist = Geometry.TwistMsg.Deserialize(deserializer);
            this.transform = Geometry.TransformStampedMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.twist);
            serializer.Write(this.transform);
        }

        public override string ToString()
        {
            return "TwistTransformUnityMsg: " +
            "\ntwist: " + twist.ToString() +
            "\ntransform: " + transform.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
